export const site = {
  origin: "https://newsletter.agentstration.io",
  name: "Agentstration Newsletter",
  languages: ["en", "fr"],
  repositoryUrl: "https://github.com/gbaudrit/agentstration-newsletter",
  productRepositoryUrl: "https://github.com/gbaudrit/agentstration",
  websiteUrl: "https://www.agentstration.io"
};

export const copy = {
  en: {
    locale: "en_US",
    languageName: "English",
    alternativeLanguage: "Français",
    skip: "Skip to content",
    menu: "Open menu",
    theme: "Change color theme",
    newsletter: "Newsletter",
    editions: "Editions",
    homeTitle: "Agentstration Newsletter",
    homeDescription: "Follow Agentstration release after release, with practical explanations of new capabilities and the technical choices behind them.",
    homeKicker: "Release by release",
    homeHeading: "The engineering story behind each Agentstration release.",
    homeBody: "A bilingual newsletter for developers and architects. Explore what changed, why it matters, and how the platform is evolving.",
    chooseLanguage: "Choose your language",
    openEnglish: "Read in English",
    openFrench: "Lire en français",
    indexTitle: "Agentstration editions",
    indexDescription: "Technical stories, release context, and architecture notes from the Agentstration project.",
    indexKicker: "All editions",
    emptyTitle: "The first edition is being prepared.",
    emptyBody: "The publication infrastructure is ready. Release content will appear here after editorial and product verification.",
    backToEditions: "All editions",
    prerelease: "Prerelease",
    published: "Published",
    releaseNotes: "GitHub Release",
    productRepository: "Product repository",
    previous: "Previous edition",
    next: "Next edition",
    noPrevious: "No previous edition",
    noNext: "No next edition",
    notFoundTitle: "Page not found",
    notFoundBody: "The requested page does not exist or is no longer available.",
    returnHome: "Return home",
    footerStatement: "Release context and technical choices from the open Agentstration project.",
    footerProduct: "Agentstration",
    footerResources: "Resources",
    mainWebsite: "Main website",
    source: "Newsletter source",
    legal: "Agentstration is an evolving open platform.",
    built: "Published as a bilingual static site."
  },
  fr: {
    locale: "fr_FR",
    languageName: "Français",
    alternativeLanguage: "English",
    skip: "Aller au contenu",
    menu: "Ouvrir le menu",
    theme: "Changer de thème",
    newsletter: "Newsletter",
    editions: "Éditions",
    homeTitle: "Newsletter Agentstration",
    homeDescription: "Suivez Agentstration version après version, avec des explications concrètes sur les nouvelles capacités et les choix techniques qui les sous-tendent.",
    homeKicker: "Version après version",
    homeHeading: "L’histoire technique derrière chaque version d’Agentstration.",
    homeBody: "Une newsletter bilingue pour les développeurs et les architectes. Découvrez ce qui change, pourquoi cela compte et comment la plateforme évolue.",
    chooseLanguage: "Choisissez votre langue",
    openEnglish: "Read in English",
    openFrench: "Lire en français",
    indexTitle: "Éditions Agentstration",
    indexDescription: "Récits techniques, contexte des versions et notes d’architecture du projet Agentstration.",
    indexKicker: "Toutes les éditions",
    emptyTitle: "La première édition est en préparation.",
    emptyBody: "L’infrastructure de publication est prête. Le contenu apparaîtra ici après les revues éditoriale et produit.",
    backToEditions: "Toutes les éditions",
    prerelease: "Préversion",
    published: "Publiée",
    releaseNotes: "GitHub Release",
    productRepository: "Dépôt produit",
    previous: "Édition précédente",
    next: "Édition suivante",
    noPrevious: "Aucune édition précédente",
    noNext: "Aucune édition suivante",
    notFoundTitle: "Page introuvable",
    notFoundBody: "La page demandée n’existe pas ou n’est plus disponible.",
    returnHome: "Retour à l’accueil",
    footerStatement: "Le contexte des versions et les choix techniques du projet ouvert Agentstration.",
    footerProduct: "Agentstration",
    footerResources: "Ressources",
    mainWebsite: "Site principal",
    source: "Sources de la newsletter",
    legal: "Agentstration est une plateforme ouverte en évolution.",
    built: "Publié sous forme de site statique bilingue."
  }
};
